# Generated by Django 5.2.4 on 2025-08-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.TextField(choices=[('check', 'На проверке'), ('approved', 'одобрено'), ('blocked', 'заблокировано')], default='approved'),
        ),
    ]
