# Generated by Django 5.2.4 on 2025-08-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.TextField(choices=[('check', 'На проверке'), ('approved', 'одобрено'), ('blocked', 'заблокировано')], default='check'),
        ),
    ]
