# Generated by Django 5.2.4 on 2025-09-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='moderator_comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
